In [2]:
import pandas as pd

In [10]:
grades={"Math":80, "English":70}

df=pd.Series(grades, dtype=str)

df

Math       80
English    70
dtype: object

In [11]:
numbers = df.tolist()
print(numbers)

['80', '70']


In [13]:
[x for x in df]

['80', '70']

In [17]:
import numpy as np
df=pd.Series(np.arange(10,100,10,dtype=np.float64),index=np.arange(101,110))

In [26]:
s = pd.Series(
    data=["001","002","003"],
    index=(1,2,3)
)

s = pd.Series(
    [int(x) for x in s],
    index=(1,2,3)
)

print([x for x in s.index])

[1, 2, 3]


In [27]:
t=(1,2,3)
[x for x in t]

[1, 2, 3]

In [28]:
np.random.seed(5555)
gold=np.random.randint(low=0,high=10,size=(7,7))
print(gold)

[[2 3 0 5 2 0 3]
 [8 8 0 7 1 5 3]
 [0 1 6 2 1 4 5]
 [4 0 8 9 9 8 7]
 [4 2 7 0 7 2 1]
 [9 8 9 2 5 0 8]
 [1 9 8 2 6 4 3]]


In [36]:
locs=np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])

In [37]:
gold[locs[:,0],locs[:,1]]

array([2, 6, 2, 8, 2])

In [43]:
a=np.linspace([17,32],[28,36],3,axis=1)
a

array([[17. , 22.5, 28. ],
       [32. , 34. , 36. ]])

In [61]:
generator = np.random.default_rng(1010)
love_scores = np.round(generator.uniform(low=0,high=100,size=10),2)
print(love_scores.shape)


(10,)


In [55]:
love_scores_t=love_scores.reshape((-1,10))
love_scores=love_scores.reshape((10,-1))

In [59]:
np.abs(love_scores_t-love_scores)

array([[ 0.  , 44.08, 82.27, 88.65, 75.38, 65.11, 31.44, 46.99,  1.11,
        55.19],
       [44.08,  0.  , 38.19, 44.57, 31.3 , 21.03, 12.64,  2.91, 45.19,
        11.11],
       [82.27, 38.19,  0.  ,  6.38,  6.89, 17.16, 50.83, 35.28, 83.38,
        27.08],
       [88.65, 44.57,  6.38,  0.  , 13.27, 23.54, 57.21, 41.66, 89.76,
        33.46],
       [75.38, 31.3 ,  6.89, 13.27,  0.  , 10.27, 43.94, 28.39, 76.49,
        20.19],
       [65.11, 21.03, 17.16, 23.54, 10.27,  0.  , 33.67, 18.12, 66.22,
         9.92],
       [31.44, 12.64, 50.83, 57.21, 43.94, 33.67,  0.  , 15.55, 32.55,
        23.75],
       [46.99,  2.91, 35.28, 41.66, 28.39, 18.12, 15.55,  0.  , 48.1 ,
         8.2 ],
       [ 1.11, 45.19, 83.38, 89.76, 76.49, 66.22, 32.55, 48.1 ,  0.  ,
        56.3 ],
       [55.19, 11.11, 27.08, 33.46, 20.19,  9.92, 23.75,  8.2 , 56.3 ,
         0.  ]])

In [63]:
love_scores[None,:]

array([[ 9.5 , 53.58, 91.77, 98.15, 84.88, 74.61, 40.94, 56.49,  8.39,
        64.69]])

In [64]:
np.set_printoptions(linewidth=999)

np.abs(love_scores[:,None]-love_scores[None,:])

array([[ 0.  , 44.08, 82.27, 88.65, 75.38, 65.11, 31.44, 46.99,  1.11, 55.19],
       [44.08,  0.  , 38.19, 44.57, 31.3 , 21.03, 12.64,  2.91, 45.19, 11.11],
       [82.27, 38.19,  0.  ,  6.38,  6.89, 17.16, 50.83, 35.28, 83.38, 27.08],
       [88.65, 44.57,  6.38,  0.  , 13.27, 23.54, 57.21, 41.66, 89.76, 33.46],
       [75.38, 31.3 ,  6.89, 13.27,  0.  , 10.27, 43.94, 28.39, 76.49, 20.19],
       [65.11, 21.03, 17.16, 23.54, 10.27,  0.  , 33.67, 18.12, 66.22,  9.92],
       [31.44, 12.64, 50.83, 57.21, 43.94, 33.67,  0.  , 15.55, 32.55, 23.75],
       [46.99,  2.91, 35.28, 41.66, 28.39, 18.12, 15.55,  0.  , 48.1 ,  8.2 ],
       [ 1.11, 45.19, 83.38, 89.76, 76.49, 66.22, 32.55, 48.1 ,  0.  , 56.3 ],
       [55.19, 11.11, 27.08, 33.46, 20.19,  9.92, 23.75,  8.2 , 56.3 ,  0.  ]])

In [65]:
generator = np.random.default_rng(80085)
scores = np.round(generator.uniform(low=30,high=100,size=15))
print(scores)

[68. 36. 76. 57. 56. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


In [71]:
scores[np.nonzero(scores<60)][0:3]=0

In [72]:
scores

array([68., 36., 76., 57., 56., 54., 63., 64., 36., 88., 80., 82., 84., 76., 42.])

In [73]:
field = np.zeros(shape=(10,10))
print(field)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [74]:
import tensorflow as tf

In [75]:
import pandas as pd
left = pd.DataFrame({
   'id':[1,2,3,4,5],
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
   'subject_id':['sub1','sub2','sub4','sub6','sub5']})
right = pd.DataFrame(
   {'id':[1,2,3,4,5],
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
   'subject_id':['sub2','sub4','sub3','sub6','sub5']})

In [77]:
right

id   Name subject_id
0   1  Billy       sub2
1   2  Brian       sub4
2   3   Bran       sub3
3   4  Bryce       sub6
4   5  Betty       sub5

In [78]:
left

id    Name subject_id
0   1    Alex       sub1
1   2     Amy       sub2
2   3   Allen       sub4
3   4   Alice       sub6
4   5  Ayoung       sub5

In [98]:
student = pd.read_csv('F:/student.csv')
course = pd.read_csv('F:/course.csv')
teacher = pd.read_csv('F:/teacher.csv')
sc = pd.read_csv('F:/sc.csv')